name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.0.0-httpupgrade.4
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.1
  permission_handler: ^8.3.0
  provider: ^6.0.1
  google_maps_webservice:
    git:
      url: https://github.com/sushinps/google_maps_webservice.git
      path: ./
  google_api_headers: ^1.1.1
  tuple: ^2.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
